basePath: /v0.1

swagger: "2.0"


info:
  title: "{{title}}"
  description: "This is an Alpha version of the persephone web API."
  version: "0.1"

schemes:
  - http
  - https

consumes:
  - application/json
  - multipart/form-data

produces:
  - application/json

paths:
  /audio:
    post:
      summary: "Upload an audio file"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: audioFile
          type: file
          required: true
      responses:
        201:
          description: success
  /audio/{audioID}:
    get:
      summary: "Get information about an uploaded audio file"
      produces:
        - application/json
      parameters:
        - name: audioID
          in: path
          description: "ID of audio file to return information about"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/audioFileInformation"
        404:
          description: "Audio file ID not found"

  /utterance:
    post:
      summary: "Upload a new utterance"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: wavFile
          type: file
          required: true
        - in: formData
          name: transcriptionFile
          type: file
          required: true
      responses:
        201:
          description: success

definitions:
  audioFileInformation:
    type: "object"
    required:
    - "name"
    - "fileURL"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "recording_123.wav"
      fileURL:
        type: "string"
        example: "/path/to/file/recording_123.wav"
