basePath: /v0.1

swagger: "2.0"


info:
  title: "{{title}}"
  description: "This is an Alpha version of the persephone web API."
  version: "0.1"

schemes:
  - http
  - https

consumes:
  - application/json
  - multipart/form-data

produces:
  - application/json

paths:
  /audio:
    post:
      summary: "Upload an audio file"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: audioFile
          type: file
          required: true
      responses:
        201:
          description: success
  /audio/{audioID}:
    get:
      summary: "Get information about an uploaded audio file"
      produces:
        - application/json
      parameters:
        - name: audioID
          in: path
          description: "ID of audio file to return information about"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/audioFileInformation"
        404:
          description: "Audio file ID not found"
  /corpus:
    get:
      summary: "Retrieve all models that are currently available"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/corpusInformation"
  /transcription:
    post:
      summary: "Upload an transcription file"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: transcriptionFile
          type: file
          required: true
      responses:
        201:
          description: success

  /transcription/{transcriptionID}:
    get:
      summary: "Get information about an uploaded transcription file"
      produces:
        - application/json
      parameters:
        - name: transcriptionID
          in: path
          description: "ID of transcription file to return information about"
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/transcriptionFileInformation"
        404:
          description: "Audio file ID not found"

  /utterance:
    post:
      summary: "Upload a new utterance"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: wavFile
          type: file
          required: true
        - in: formData
          name: transcriptionFile
          type: file
          required: true
      responses:
        201:
          description: success

  /model:
    get:
      summary: "Retrieve all models that are currently available"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/modelInformation"
  /backend:
    get:
      summary: "Get information about the backend package processing transcriptions"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/backendInformation"

definitions:
  audioFileInformation:
    type: "object"
    required:
    - "name"
    - "fileURL"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "recording_123.wav"
      fileURL:
        type: "string"
        example: "/path/to/file/recording_123.wav"
  backendInformation:
    type: "object"
    required:
    - "name"
    - "version"
    properties:
      name:
        type: "string"
        example: "Persephone"
        description: "Name of backend software package performing the transcription"
      version:
        type: "string"
        description: "Version of backend software package performing the transcription"
      projectURL:
        type: "string"
        example: "http://persephone.readthedocs.io/en/latest/"
        description: "URL for this project"
  corpusInformation:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        description: "The name of this corpus"
      utterances:
        type: array
        items:
          $ref: "#/definitions/utteranceInformation"
        description: "All utterances that this corpus contains"
  transcriptionFileInformation:
    type: "object"
    required:
    - "name"
    - "fileURL"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "transcription.txt"
      manuallyGenerated:
        type: boolean
        description: "Flag if this file was generated manually. Useful for keeping track of training files"
      fileURL:
        type: "string"
        example: "/path/to/file/transcription.txt"
  modelInformation:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "na_example_small"
  utteranceInformation:
    type: "object"
