basePath: /v0.1

swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

schemes:
  - http
  - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /hello_world:
    get:
      operationId: api.hello_world
      responses:
        200:
          description: success
