basePath: /v0.1

swagger: "2.0"


info:
  title: "{{title}}"
  description: "This is an Alpha version of the persephone web API."
  version: "0.1"

schemes:
  - http
  - https

consumes:
  - application/json
  - multipart/form-data

produces:
  - application/json

paths:
  /audio:
    post:
      summary: "Upload an audio file"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: audioFile
          type: file
          required: true
      responses:
        201:
          description: success

  /utterance:
    post:
      summary: "Upload a new utterance"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: wavFile
          type: file
          required: true
        - in: formData
          name: transcriptionFile
          type: file
          required: true
      responses:
        201:
          description: success
